### ISSUE TITLE
Error library when I use install with npm

### ISSUE THREAD

**Issue by Vitaliy-Opaynitch** [ain/smartbanner.js#690] opened 2023-10-25 16:18 UTC
__Steps to reproduce__:

1. I have Vue 2 application
2. I try to implement library with yarn add smartbanner.js (we use yarn on project)

__What happens__: After adding tags and links to my index.html and run App I see error on my console `Uncaught SyntaxError: Unexpected token '<'` and baner don`t display on my page

__What should happen__: Library should work, also library work if I use cdnjs.js method

**Comment by ain** [comment] 2023-10-25 16:49
Thanks for the report.

1. Please double-check if you have added the correct `meta` tags into the head of your HTML file
2. If not helping, post the contents (or the meta tags) of your `index.html` file here so it can be tested

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-25 18:22
My meta tags correct, because library work with with cdn.js method

```
<meta name="smartbanner:title" content="My app">
<meta name="smartbanner:author" content="Translation">
<meta name="smartbanner:price" content="App">
<meta name="smartbanner:price-suffix-apple" content="Translation">
<meta name="smartbanner:price-suffix-google" content="Translation">
<meta name="smartbanner:custom-design-modifier" content="ios">
<meta name="smartbanner:hide-ttl" content="12000">
<meta name="smartbanner:disable-positioning" content="true">
<meta name="smartbanner:icon-apple" content="/static/icons_app/logo_mobile_app.png">
<meta name="smartbanner:icon-google" content="/static/icons_app/logo_mobile_app.png">
<meta name="smartbanner:button" content="Download">
<meta name="smartbanner:button-url-apple" content="https://apps.apple.com/ua/app/...">
<meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/...">
<meta name="smartbanner:enabled-platforms" content="android,ios">
<meta name="smartbanner:close-label" content="Close">
```

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-25 18:27
<link rel="stylesheet" href="node_modules/smartbanner.js/dist/smartbanner.min.css">
<script src="node_modules/smartbanner.js/dist/smartbanner.min.js"></script>

my links

**Comment by ain** [comment] 2023-10-25 18:56
Which version of `smartbanner.js` are you using?

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-25 18:59
![image](https://github.com/ain/smartbanner.js/assets/88537229/f192dd5c-aa4a-4dd2-a0b1-dc9a8df6898e)

Last, 1.19.3

**Comment by ain** [comment] 2023-10-25 19:06
1. Did you include the 2 tags for CSS and JS in `<head>`?
2. Have you tried including unminified version, e.g. `<script src="node_modules/smartbanner.js/dist/smartbanner.js"></script>`? 

You're very likely dealing with the implementation error, because `dist/index.html` of `1.19.3` does work based on the same script.

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-25 19:55
1. Yes in <head>
2. Yes I try, but have the same error
3. Already try, dont work for me

**Comment by ain** [comment] 2023-10-25 20:06
If you include the unminified source, which line does the stack trace point to?

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-26 06:55
The same issue
![image](https://github.com/ain/smartbanner.js/assets/88537229/74fae79c-27f3-4812-8cc1-51e8c6e2a847)

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-26 06:58
Maybe I should try earlier versions?

**Comment by ain** [comment] 2023-10-26 07:00
I don't think it will help, the problem is not in the smartbanner. You can easily prove it locally by running the `index.html`
 in `dist/` folder.

Also `smartbanner.js:1` does not have any `<` anywhere, see https://github.com/ain/smartbanner.js/blob/main/dist/smartbanner.js#L1

You're most certainly dealing with a corrupt file and/or process.

**Comment by ain** [comment] 2023-10-26 07:01
Also please note that you're not using NPM, but Yarn.

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-27 09:53
So, I will use with cdnjs. Does smartbanner support multilanguage content? I mean texts which we put on meta-tag.

**Comment by Vitaliy-Opaynitch** [comment] 2023-10-27 09:59
And does this library support alternative text and behavior for the "open" button if the app is already installed?

**Comment by ain** [comment] 2023-10-27 10:49
See #586 for a language-specific discussion.

Given the current scope of the discussion, closing the issue.

**Closed by ain** 2023-10-27 10:49 UTC
