### ISSUE TITLE
Not Working on latest Chrome on Ios but working on safari

### ISSUE THREAD

**Issue by alinoudev** [ain/smartbanner.js#136] opened 2019-11-13 02:31 UTC
__Steps to reproduce__:

Go to chrome om Ios and try it. Working for safari

__What happens__:
it just opens the same page in another browser rather than opening the app store
__What should happen__n
it should go to app store

**Comment by alinoudev** [comment] 2019-11-13 04:34
For time being i fixed it by removing _blank from here line 408
`return "<div class=\"smartbanner smartbanner--".concat(modifier, " js_smartbanner\">\n      <a href=\"javascript:void();\" class=\"smartbanner__exit js_smartbanner__exit\" aria-label=\"").concat(this.closeLabel, "\"></a>\n      <div class=\"smartbanner__icon\" style=\"background-image: url(").concat(this.icon, ");\"></div>\n      <div class=\"smartbanner__info\">\n        <div>\n          <div class=\"smartbanner__info__title\">").concat(this.options.title, "</div>\n          <div class=\"smartbanner__info__author\">").concat(this.options.author, "</div>\n          <div class=\"smartbanner__info__price\">").concat(this.options.price).concat(this.priceSuffix, "</div>\n        </div>\n      </div>\n      <a href=\"").concat(this.buttonUrl, "\" class=\"smartbanner__button\" rel=\"noopener\" aria-label=\"").concat(this.options.button, "\"><span class=\"smartbanner__button__label\">").concat(this.options.button, "</span></a>\n    </div>");`

**Comment by ain** [comment] 2019-11-13 19:19
Dupe of #128.

**Closed by ain** 2019-11-13 19:19 UTC
Labels: duplicate
